[package]
name = "yabinero"
version = "0.1.0"
authors = ["Nicolas Salguero <nicolas.salguero@laposte.net>"]
edition = "2018"
license = "GPL-3.0+"

[dependencies]
fltk = "^0.4"
rand = "^0.7"
rodio = "^0.11"
preferences = "^1.1"
