[package]
name = "yabinero"
version = "1.16.0"
authors = ["Nicolas Salguero <nicolas.salguero@laposte.net>"]
edition = "2018"
license = "GPL-3.0+"

[dependencies]
locale_config = "^0.3"
fltk = "^0.9"
rand = "^0.7"
rodio = "^0.11"
preferences = "^1.1"
gettext = "^0.4"
tr = { version = "^0.1", features = ["gettext"], default-features = false }
enum-iterator = "^0.6"
chrono = "^0.4"
lazy_static = "^1.4"

[target.'cfg(windows)'.dependencies]
gettext-sys = { version = "^0.19", features = ["gettext-system"] }
