[package]
name = "yabinero"
version = "1.12.0"
authors = ["Nicolas Salguero <nicolas.salguero@laposte.net>"]
edition = "2018"
license = "GPL-3.0+"

[dependencies]
fltk = "^0.7"
rand = "^0.7"
rodio = "^0.11"
preferences = "^1.1"
tr = "^0.1"
enum-iterator = "^0.6"
chrono = "^0.4"
